version "4.7"
#include "zscript/armour/HHArmourNerf.zs"
#include "zscript/armour/HHArmourNerfHandler.zs"
#include "zscript/armour/HHArmourType_HDArmourWorn.zs"
#include "zscript/armour/HHArmourTypeHandler.zs"

#include "zscript/helmet/base.zs"
#include "zscript/helmet/HasHelmet.zs"
#include "zscript/helmet/HHelmetSkinHandler.zs"
#include "zscript/helmet/HHelmetSpawner.zs"
#include "zscript/helmet/HHSpawnType.zs"
#include "zscript/helmet/HHSpawnType_Default.zs"

#include "zscript/HHHandler.zs"
#include "zscript/HHWhitelistMenu.zs"
